
spring:
 
  datasource:
    url: jdbc:mysql://localhost:3306/patient_db
    username: root
    password: 
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka # URL of Eureka Server
